/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/queues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_queues"];
    put?: never;
    post: operations["create_queue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/queues/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_queue"];
    put?: never;
    post?: never;
    delete: operations["delete_queue"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/queues/{name}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["receive_messages"];
    put?: never;
    post: operations["send_messages"];
    delete: operations["delete_batch"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/queues/{name}/messages/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_message"];
    options?: never;
    head?: never;
    patch: operations["change_visibility"];
    trace?: never;
  };
  "/v1/queues/{name}/purge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["purge_queue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/queues/{name}/subscriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_queue_subscriptions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/topics/{pattern}/subscriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_topic_subscriptions"];
    put?: never;
    post: operations["subscribe_queue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/topics/{pattern}/subscriptions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["unsubscribe_queue"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/topics/{routing_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["send_topic"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ChangeVisibilityRequest: {
      /** Format: int32 */
      vt: number;
    };
    ChangeVisibilityResponse: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      visible_at: string;
    };
    CreateQueueRequest: {
      fifo?: boolean;
      name: string;
    };
    DeleteBatchRequest: {
      ids: number[];
    };
    DeletedResponse: {
      deleted: number[];
    };
    ErrorResponse: {
      code: string;
      message: string;
    };
    MessageResponse: {
      /** Format: date-time */
      enqueued_at: string;
      headers?: unknown;
      /** Format: int64 */
      id: number;
      message: unknown;
      /** Format: int32 */
      read_count: number;
      /** Format: date-time */
      visible_at: string;
    };
    PurgeResponse: {
      /** Format: int64 */
      deleted: number;
    };
    QueueMetricsResponse: {
      name: string;
      /** Format: int64 */
      newest_msg_age_sec?: number | null;
      /** Format: int64 */
      oldest_msg_age_sec?: number | null;
      /** Format: int64 */
      queue_length: number;
      /** Format: date-time */
      scrape_time: string;
      /** Format: int64 */
      total_messages: number;
    };
    QueueResponse: {
      /** Format: date-time */
      created_at: string;
      is_partitioned: boolean;
      is_unlogged: boolean;
      name: string;
    };
    SendBody:
      | components["schemas"]["SendRequest"]
      | components["schemas"]["SendRequest"][];
    SendRequest: {
      /** Format: int32 */
      delay?: number;
      group_id?: string | null;
      headers?: unknown;
      message: unknown;
    };
    SendResponse: {
      /** Format: int64 */
      id: number;
    } | {
      ids: number[];
    };
    SubscribeRequest: {
      endpoint?: string | null;
      /** @description Opt-in to SNS notification envelope; default false means raw payload delivery. */
      envelope?: boolean;
      protocol?: string | null;
      queue_name?: string | null;
    };
    TopicMessage: {
      /** Format: int64 */
      msg_id: number;
      queue_name: string;
    };
    TopicSendRequest: {
      /** Format: int32 */
      delay?: number;
      headers?: unknown;
      message: unknown;
    };
    TopicSendResponse: {
      messages: components["schemas"]["TopicMessage"][];
      /** Format: int64 */
      queues_matched: number;
    };
    TopicSubscription: {
      /** Format: date-time */
      bound_at: string;
      endpoint: string;
      /** Format: int64 */
      id: number;
      pattern: string;
      protocol: string;
      queue_name?: string | null;
      raw_delivery: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_queues: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueResponse"][];
        };
      };
    };
  };
  create_queue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateQueueRequest"];
      };
    };
    responses: {
      /** @description Queue created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_queue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueMetricsResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_queue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Queue deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  receive_messages: {
    parameters: {
      query?: {
        /** @description Maximum number of messages to return. Default: 1. */
        max?: number;
        /** @description Long-poll wait time in seconds. Default: 0 (no wait). */
        wait?: number;
        /** @description Visibility timeout in seconds. Default: 30. */
        vt?: number;
        /** @description Return messages in FIFO order within a group. Default: false. */
        fifo?: boolean;
      };
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"][];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  send_messages: {
    parameters: {
      query?: {
        /**
         * @description Skip WAL fsync on commit. Improves throughput at the cost of durability:
         *     messages can be lost on a PostgreSQL crash. Default: false (durable).
         */
        async_commit?: boolean;
      };
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendBody"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SendResponse"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_batch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteBatchRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeletedResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_message: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
        /** @description Message ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Message deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  change_visibility: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
        /** @description Message ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeVisibilityRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangeVisibilityResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  purge_queue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PurgeResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_queue_subscriptions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Queue name */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicSubscription"][];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_topic_subscriptions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Topic pattern (glob) */
        pattern: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicSubscription"][];
        };
      };
    };
  };
  subscribe_queue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Topic pattern (glob) */
        pattern: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubscribeRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicSubscription"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  unsubscribe_queue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Topic pattern (glob) */
        pattern: string;
        /** @description Subscription ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Subscription removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  send_topic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Routing key / topic name */
        routing_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TopicSendRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicSendResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
